
project_id = "wkfzhcszhgewkvwukzes"
[functions.send-verification]
verify_jwt = false
[functions.verify-code]
verify_jwt = false

[[functions.send-verification.headers]]
name = "Access-Control-Allow-Origin"
value = "*"

[[functions.send-verification.headers]]
name = "Access-Control-Allow-Headers"
value = "authorization, x-client-info, apikey, content-type"

[[functions.verify-code.headers]]
name = "Access-Control-Allow-Origin"
value = "*"

[[functions.verify-code.headers]]
name = "Access-Control-Allow-Headers"
value = "authorization, x-client-info, apikey, content-type"